# balance sheet entries
QE = "QE"
LOANS = "Loans"
MBS = "Mortgage Backed Ssecurities"
SECURITIES = "Securities"
DEPOSITS = "Deposits"
DEBT = "Debt"
UNRESOLVED_DEBT = "Unresolved debt"
SAVINGS = "Savings"
EQUITY = "Equity"
SEC_EQUITY = "Securities equity"
MBS_EQUITY = "MBS equity"
HELICOPTER_MONEY = "Helicopter money"
RESERVES = "Reserves"
INTEREST = "Interest"
